# Generated by Django 3.0.2 on 2020-02-21 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='autor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=100, verbose_name='Изображение товара'),
        ),
    ]
