# Generated by Django 3.0.2 on 2020-02-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200221_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Цена'),
        ),
    ]
