# Generated by Django 3.0.2 on 2020-02-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200221_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_type',
        ),
        migrations.AddField(
            model_name='users',
            name='client',
            field=models.CharField(default='testClient', max_length=30, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='users',
            name='manager',
            field=models.CharField(default='testClient', max_length=30, verbose_name='Менеджер'),
        ),
    ]
