# Generated by Django 3.0.2 on 2020-02-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200223_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='client',
            field=models.CharField(blank=True, default='testClient', max_length=100, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='users',
            name='manager',
            field=models.CharField(blank=True, default='testManager', max_length=100, verbose_name='Менеджер'),
        ),
    ]
