# Generated by Django 3.0.2 on 2020-02-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200223_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('MN', 'Manager'), ('CL', 'Client')], default='test', max_length=2, verbose_name='Пользователи'),
        ),
    ]
