# Generated by Django 3.0.2 on 2020-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200223_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOfOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('НОВЫЙ', 'НОВЫЙ'), ('ПОДГОТОВКА_КП', 'ПОДГОТОВКА_КП'), ('КП', 'КП'), ('ЗАКАЗ', 'ЗАКАЗ'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', editable=False, max_length=20)),
            ],
        ),
    ]
