# Generated by Django 3.0.2 on 2020-02-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_statusoforder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusOfOrder',
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('НОВЫЙ', 'НОВЫЙ'), ('ПОДГОТОВКА_КП', 'ПОДГОТОВКА_КП'), ('КП', 'КП'), ('ЗАКАЗ', 'ЗАКАЗ'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=20),
        ),
    ]
