# Generated by Django 3.0.2 on 2020-02-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200226_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('НОВЫЙ', 'НОВЫЙ'), ('ПОДГОТОВКА_КП', 'ПОДГОТОВКА_КП'), ('КП', 'КП'), ('ЗАКАЗ', 'ЗАКАЗ'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=50),
        ),
    ]
