# Generated by Django 3.0.2 on 2020-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200226_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_and_time_of_change_of_order',
            field=models.DateTimeField(verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ОПЛАЧЕНО', 'ОПЛАЧЕНО'), ('НЕОПЛАЧЕНО', 'НЕОПЛАЧЕНО'), ('В ДОСТАВКЕ', 'В ДОСТАВКЕ')], default='НЕОПЛАЧЕНО', max_length=50),
        ),
    ]
